# Generated by Django 4.2.7 on 2024-02-11 09:12

from django.db import migrations, models
import utils.hash_storage


class Migration(migrations.Migration):

    dependencies = [
        ("app_users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                null=True,
                storage=utils.hash_storage.HashStorage(),
                upload_to=utils.hash_storage.user_avatar_images,
                verbose_name="Аватар",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="city_name",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Город"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True, max_length=24, null=True, verbose_name="Телефон"
            ),
        ),
    ]
